/* Legal Help India — अतिरिक्त माहिती: नवे विषय (नागरिक/मुले/कामगार), शिक्षण विषयाची सुधारणा, संविधानाची प्रस्तावना */
(function(){
const D=window.LHI_DATA;if(!D)return;
const tr=(mr,hi,en)=>({mr:mr,hi:hi,en:en});
const H={laws:tr("मुख्य कायदे","मुख्य कानून","Key Laws"),rights:tr("तुमचे हक्क","आपके अधिकार","Your Rights"),todo:tr("काय करावे","क्या करें","What To Do")};

/* --- शीर्षके मॉकअपशी जुळवली --- */
D.TOPICS.police.title=tr("पोलीस / अटकेसंबंधी हक्क","पुलिस / गिरफ्तारी संबंधी अधिकार","Police & Arrest Rights");
D.TOPICS.senior.title=tr("वरिष्ठ नागरिकांचे हक्क","वरिष्ठ नागरिकों के अधिकार","Senior Citizens' Rights");

/* --- शिक्षण: आता फक्त शिक्षणाशी संबंधित; नोकरीची माहिती "कामगार हक्क" मध्ये हलवली --- */
D.TOPICS.education.title=tr("शिक्षणाशी संबंधित हक्क","शिक्षा से संबंधित अधिकार","Education Rights");
D.TOPICS.education.sections=[
 {heading:H.laws,items:tr(["शिक्षण हक्क कायदा (RTE), २००९","भारतीय संविधान — कलम २१अ (शिक्षणाचा हक्क)"],["शिक्षा का अधिकार अधिनियम (RTE), 2009","भारतीय संविधान — अनुच्छेद 21अ (शिक्षा का अधिकार)"],["Right to Education Act (RTE), 2009","Constitution of India — Article 21A (Right to Education)"])},
 {heading:H.rights,items:tr(["६ ते १४ वयोगटातील मोफत व सक्तीच्या शिक्षणाचा हक्क","खासगी विनाअनुदानित शाळांत प्रवेशस्तरावर २५% जागा दुर्बल व वंचित घटकांसाठी राखीव","शारीरिक शिक्षा व मानसिक छळास मनाई","शाळेत जात, धर्म किंवा लिंगावरून भेदभावास मनाई"],["6 से 14 वर्ष के बच्चों को मुफ्त व अनिवार्य शिक्षा का अधिकार","निजी गैर-सहायता प्राप्त स्कूलों में प्रवेश स्तर पर 25% सीटें कमज़ोर व वंचित वर्गों के लिए आरक्षित","शारीरिक दंड व मानसिक उत्पीड़न पर रोक","स्कूल में जाति, धर्म या लिंग के आधार पर भेदभाव पर रोक"],["Free and compulsory education for children aged 6 to 14","25% seats at entry level in private unaided schools reserved for disadvantaged groups","Corporal punishment and mental harassment are prohibited","No discrimination in school on caste, religion or gender"])},
 {heading:H.todo,items:tr(["प्रवेश नाकारल्यास शिक्षण अधिकारी / गटशिक्षणाधिकाऱ्याकडे लेखी तक्रार करा","RTE संबंधी तक्रारींसाठी राज्य बाल हक्क संरक्षण आयोगाशी संपर्क करा","शाळेची मान्यता किंवा फी संबंधी तक्रार शिक्षण विभागाकडे करा"],["प्रवेश से इनकार होने पर शिक्षा अधिकारी / खंड शिक्षा अधिकारी को लिखित शिकायत दें","RTE संबंधी शिकायतों के लिए राज्य बाल अधिकार संरक्षण आयोग से संपर्क करें","स्कूल की मान्यता या फीस संबंधी शिकायत शिक्षा विभाग को करें"],["If admission is denied, complain in writing to the Education Officer / Block Education Officer","For RTE issues, contact the State Commission for Protection of Child Rights","Report school recognition or fee issues to the education department"])}
];
D.TOPICS.education.related=["२१अ","२९","३०"];
D.TOPICS.education.faqs=[D.TOPICS.education.faqs[0],
 {q:tr("खासगी शाळेत RTE अंतर्गत मोफत प्रवेश मिळतो का?","निजी स्कूल में RTE के तहत मुफ्त प्रवेश मिलता है क्या?","Can my child get free admission in a private school under RTE?"),
  a:tr("होय. पात्र आर्थिक/सामाजिक दुर्बल कुटुंबांतील मुलांसाठी खासगी विनाअनुदानित शाळांत प्रवेशस्तरावर २५% जागा राखीव असतात. अर्ज राज्य सरकारच्या RTE पोर्टलवर ठरलेल्या कालावधीत करावा लागतो.","हाँ। पात्र आर्थिक/सामाजिक रूप से कमज़ोर परिवारों के बच्चों के लिए निजी गैर-सहायता प्राप्त स्कूलों में प्रवेश स्तर पर 25% सीटें आरक्षित होती हैं। आवेदन राज्य सरकार के RTE पोर्टल पर निर्धारित अवधि में करना होता है।","Yes. 25% seats at entry level in private unaided schools are reserved for eligible economically/socially disadvantaged children. Apply on your State's RTE portal within the notified window.")}];

/* --- नवे विषय --- */
D.TOPICS.citizens={icon:"👥",color:"#0b3d91",title:tr("नागरिकांचे हक्क","नागरिकों के अधिकार","Citizens' Rights"),
 sections:[
  {heading:H.laws,items:tr(["भारतीय संविधान — भाग ३ (मूलभूत हक्क)","माहितीचा अधिकार कायदा (RTI), २००५","कायदेशीर सेवा प्राधिकरण कायदा, १९८७ (मोफत कायदेशीर मदत)","मानवी हक्क संरक्षण कायदा, १९९३"],["भारतीय संविधान — भाग 3 (मौलिक अधिकार)","सूचना का अधिकार अधिनियम (RTI), 2005","विधिक सेवा प्राधिकरण अधिनियम, 1987 (मुफ्त कानूनी सहायता)","मानव अधिकार संरक्षण अधिनियम, 1993"],["Constitution of India — Part III (Fundamental Rights)","Right to Information Act (RTI), 2005","Legal Services Authorities Act, 1987 (free legal aid)","Protection of Human Rights Act, 1993"])},
  {heading:H.rights,items:tr(["समानतेचा हक्क (कलम १४–१८)","स्वातंत्र्याचा हक्क (कलम १९–२२)","शोषणाविरुद्धचा हक्क (कलम २३–२४)","धर्मस्वातंत्र्याचा हक्क (कलम २५–२८)","सांस्कृतिक व शैक्षणिक हक्क (कलम २९–३०)","घटनात्मक उपायांचा हक्क (कलम ३२)"],["समानता का अधिकार (अनुच्छेद 14–18)","स्वतंत्रता का अधिकार (अनुच्छेद 19–22)","शोषण के विरुद्ध अधिकार (अनुच्छेद 23–24)","धर्म की स्वतंत्रता का अधिकार (अनुच्छेद 25–28)","सांस्कृतिक व शैक्षिक अधिकार (अनुच्छेद 29–30)","संवैधानिक उपचारों का अधिकार (अनुच्छेद 32)"],["Right to Equality (Articles 14–18)","Right to Freedom (Articles 19–22)","Right against Exploitation (Articles 23–24)","Right to Freedom of Religion (Articles 25–28)","Cultural and Educational Rights (Articles 29–30)","Right to Constitutional Remedies (Article 32)"])},
  {heading:H.todo,items:tr(["मूलभूत हक्काचा भंग झाल्यास उच्च न्यायालयात (कलम २२६) किंवा सर्वोच्च न्यायालयात (कलम ३२) याचिका दाखल करता येते","सरकारी कामकाजाची माहिती हवी असल्यास RTI अर्ज करा","पात्र व्यक्तींना जिल्हा विधी सेवा प्राधिकरणाकडून मोफत वकील मिळू शकतो (NALSA हेल्पलाइन १५१००)"],["मौलिक अधिकारों का हनन होने पर उच्च न्यायालय (अनुच्छेद 226) या सर्वोच्च न्यायालय (अनुच्छेद 32) में याचिका दायर की जा सकती है","सरकारी कामकाज की जानकारी के लिए RTI आवेदन करें","पात्र व्यक्तियों को ज़िला विधिक सेवा प्राधिकरण से मुफ्त वकील मिल सकता है (NALSA हेल्पलाइन 15100)"],["If a fundamental right is violated, file a petition in the High Court (Article 226) or Supreme Court (Article 32)","Use an RTI application to seek information on government work","Eligible persons can get a free lawyer from the District Legal Services Authority (NALSA helpline 15100)"])}
 ],
 related:["१४","१९","२१","३२"],
 faqs:[
  {q:tr("RTI अर्जाची फी किती असते?","RTI आवेदन की फीस कितनी होती है?","What is the fee for an RTI application?"),a:tr("केंद्र सरकारच्या कार्यालयांसाठी अर्ज फी रु. १० आहे; राज्यांची फी वेगवेगळी असू शकते. दारिद्र्यरेषेखालील (BPL) व्यक्तींना फी माफ असते.","केंद्र सरकार के कार्यालयों के लिए आवेदन फीस रु. 10 है; राज्यों की फीस अलग हो सकती है। गरीबी रेखा से नीचे (BPL) के व्यक्तियों को फीस माफ है।","The application fee is Rs. 10 for Central Government offices; States may charge differently. Persons below the poverty line (BPL) are exempt from the fee.")},
  {q:tr("मोफत वकील कोणाला मिळू शकतो?","मुफ्त वकील किसे मिल सकता है?","Who can get a free lawyer?"),a:tr("महिला, बालके, अनुसूचित जाती/जमाती, अपंग व्यक्ती, कोठडीतील व्यक्ती, औद्योगिक कामगार आणि राज्य सरकारने ठरवलेल्या उत्पन्न मर्यादेखालील व्यक्ती. जिल्हा विधी सेवा प्राधिकरणाकडे अर्ज करा.","महिलाएँ, बच्चे, अनुसूचित जाति/जनजाति, दिव्यांग व्यक्ति, हिरासत में व्यक्ति, औद्योगिक कामगार और राज्य सरकार द्वारा तय आय सीमा से कम आय वाले व्यक्ति। ज़िला विधिक सेवा प्राधिकरण में आवेदन करें।","Women, children, SC/ST members, persons with disabilities, persons in custody, industrial workmen and persons below the income limit set by the State. Apply to the District Legal Services Authority.")}
 ]};

D.TOPICS.children={icon:"🧒",color:"#0b3d91",title:tr("मुलांचे हक्क","बच्चों के अधिकार","Children's Rights"),
 sections:[
  {heading:H.laws,items:tr(["शिक्षण हक्क कायदा (RTE), २००९","लैंगिक अत्याचारांपासून बालकांचे संरक्षण कायदा (POCSO), २०१२","बालकामगार (प्रतिबंध व नियमन) कायदा, १९८६ (सुधारित २०१६)","बाल विवाह प्रतिबंध कायदा, २००६","बाल न्याय (काळजी व संरक्षण) कायदा, २०१५"],["शिक्षा का अधिकार अधिनियम (RTE), 2009","यौन अपराधों से बालकों का संरक्षण अधिनियम (POCSO), 2012","बालश्रम (प्रतिषेध एवं विनियमन) अधिनियम, 1986 (संशोधित 2016)","बाल विवाह प्रतिषेध अधिनियम, 2006","किशोर न्याय (बालकों की देखरेख एवं संरक्षण) अधिनियम, 2015"],["Right to Education Act (RTE), 2009","Protection of Children from Sexual Offences Act (POCSO), 2012","Child and Adolescent Labour (Prohibition and Regulation) Act, 1986 (amended 2016)","Prohibition of Child Marriage Act, 2006","Juvenile Justice (Care and Protection of Children) Act, 2015"])},
  {heading:H.rights,items:tr(["६ ते १४ वयोगटात मोफत व सक्तीचे शिक्षण","लैंगिक अत्याचार व शोषणापासून संरक्षण","१४ वर्षांखालील मुलांना कामावर ठेवण्यास मनाई","काळजी, संरक्षण व पुनर्वसनाचा हक्क"],["6 से 14 वर्ष तक मुफ्त व अनिवार्य शिक्षा","यौन उत्पीड़न व शोषण से संरक्षण","14 वर्ष से कम उम्र के बच्चों से काम करवाने पर रोक","देखरेख, संरक्षण व पुनर्वास का अधिकार"],["Free and compulsory education from age 6 to 14","Protection from sexual abuse and exploitation","Employing children below 14 years is prohibited","Right to care, protection and rehabilitation"])},
  {heading:H.todo,items:tr(["मुलावर अत्याचार झाल्यास चाइल्डलाइन १०९८ वर कॉल करा (२४ तास, मोफत)","पोलीस स्टेशन किंवा बाल कल्याण समितीकडे (CWC) तक्रार करा","शाळेने प्रवेश नाकारल्यास शिक्षण विभागाकडे तक्रार करा"],["बच्चे के साथ अत्याचार होने पर चाइल्डलाइन 1098 पर कॉल करें (24 घंटे, निःशुल्क)","पुलिस स्टेशन या बाल कल्याण समिति (CWC) में शिकायत करें","स्कूल द्वारा प्रवेश से इनकार पर शिक्षा विभाग में शिकायत करें"],["If a child is abused, call Childline 1098 (24 hours, free)","Complain to the police station or the Child Welfare Committee (CWC)","If a school refuses admission, complain to the education department"])}
 ],
 related:["२१अ","२४"],
 faqs:[
  {q:tr("मुलावर अत्याचार झाल्यास कुठे तक्रार करावी?","बच्चे के साथ अत्याचार होने पर कहाँ शिकायत करें?","Where to report abuse of a child?"),a:tr("चाइल्डलाइन १०९८, जवळचे पोलीस स्टेशन किंवा POCSO e-Box (ऑनलाइन) वर तक्रार करता येते. POCSO अंतर्गत अशा घटनेची माहिती असूनही ती न कळवणे हाही गुन्हा आहे.","चाइल्डलाइन 1098, नज़दीकी पुलिस स्टेशन या POCSO e-Box (ऑनलाइन) पर शिकायत की जा सकती है। POCSO के तहत ऐसी घटना की जानकारी होने पर भी सूचित न करना अपराध है।","Report to Childline 1098, the nearest police station, or the POCSO e-Box (online). Under POCSO, knowing about such an incident and not reporting it is itself an offence.")},
  {q:tr("बालकामगार ठेवणे कायदेशीर आहे का?","बालश्रम करवाना कानूनी है क्या?","Is employing child labour legal?"),a:tr("१४ वर्षांखालील मुलांना कामावर ठेवणे बेकायदेशीर आहे (मर्यादित कौटुंबिक/कला-क्षेत्रातील अपवाद वगळता). १४ ते १८ वयोगटातील किशोरांना धोकादायक उद्योगांत ठेवण्यास मनाई आहे.","14 वर्ष से कम उम्र के बच्चों से काम करवाना गैरकानूनी है (सीमित पारिवारिक/कला क्षेत्र के अपवादों को छोड़कर)। 14 से 18 वर्ष के किशोरों को खतरनाक उद्योगों में लगाना मना है।","Employing children below 14 is illegal (except limited family/arts-related exceptions). Adolescents aged 14 to 18 cannot be employed in hazardous industries.")}
 ]};

D.TOPICS.labour={icon:"👷",color:"#0b3d91",title:tr("कामगार हक्क","श्रमिक अधिकार","Labour Rights"),
 sections:[
  {heading:H.laws,items:tr(["किमान वेतन कायदा / वेतन संहिता (Code on Wages), २०१९","औद्योगिक विवाद कायदा, १९४७","कर्मचारी भविष्य निर्वाह निधी (EPF) कायदा, १९५२","ग्रॅच्युईटी प्रदान कायदा, १९७२","कर्मचारी राज्य विमा (ESI) कायदा, १९४८"],["न्यूनतम वेतन अधिनियम / वेतन संहिता (Code on Wages), 2019","औद्योगिक विवाद अधिनियम, 1947","कर्मचारी भविष्य निधि (EPF) अधिनियम, 1952","ग्रेच्युटी भुगतान अधिनियम, 1972","कर्मचारी राज्य बीमा (ESI) अधिनियम, 1948"],["Minimum Wages Act / Code on Wages, 2019","Industrial Disputes Act, 1947","Employees' Provident Funds (EPF) Act, 1952","Payment of Gratuity Act, 1972","Employees' State Insurance (ESI) Act, 1948"])},
  {heading:H.rights,items:tr(["किमान वेतनाचा हक्क","समान कामासाठी समान वेतन","कामाच्या ठिकाणी सुरक्षिततेचा हक्क","EPF व ग्रॅच्युईटीचा हक्क (ग्रॅच्युईटी साधारणतः ५ वर्षे सेवेनंतर)","पात्र कामगारांना ESI चे वैद्यकीय लाभ","बेकायदेशीर बडतर्फीविरुद्ध दाद मागण्याचा हक्क"],["न्यूनतम वेतन का अधिकार","समान काम के लिए समान वेतन","कार्यस्थल पर सुरक्षा का अधिकार","EPF व ग्रेच्युटी का अधिकार (ग्रेच्युटी सामान्यतः 5 वर्ष सेवा के बाद)","पात्र कर्मचारियों को ESI के चिकित्सा लाभ","अवैध बर्खास्तगी के विरुद्ध न्याय माँगने का अधिकार"],["Right to minimum wages","Equal pay for equal work","Right to a safe workplace","EPF and gratuity (gratuity generally after 5 years of service)","ESI medical benefits for eligible workers","Right to seek remedy against unlawful termination"])},
  {heading:H.todo,items:tr(["पगार थकल्यास आधी नियोक्त्याकडे लेखी तक्रार करा, नंतर कामगार आयुक्त कार्यालयात तक्रार करा","बेकायदेशीर बडतर्फीत कामगार न्यायालयात दाद मागता येते","नियुक्तीपत्र, वेतन पावत्या व हजेरीचे पुरावे जपून ठेवा","टीप: कामगार कायद्यांचे श्रम संहितांमध्ये रूपांतर होत असल्याने काही तरतुदी बदलू शकतात; ताज्या माहितीसाठी कामगार आयुक्त कार्यालयाशी संपर्क करा"],["वेतन बकाया होने पर पहले नियोक्ता को लिखित शिकायत दें, फिर श्रम आयुक्त कार्यालय में शिकायत करें","अवैध बर्खास्तगी में श्रम न्यायालय में न्याय माँगा जा सकता है","नियुक्ति पत्र, वेतन पर्चियाँ व उपस्थिति के सबूत सुरक्षित रखें","नोट: श्रम कानूनों का श्रम संहिताओं में रूपांतरण हो रहा है, इसलिए कुछ प्रावधान बदल सकते हैं; ताज़ा जानकारी के लिए श्रम आयुक्त कार्यालय से संपर्क करें"],["If wages are unpaid, first complain in writing to the employer, then to the Labour Commissioner's office","For unlawful termination, approach the Labour Court","Keep your appointment letter, salary slips and attendance proof","Note: labour laws are being consolidated into Labour Codes, so some provisions may change; check with the Labour Commissioner's office for the latest position"])}
 ],
 related:["१६","२३"],
 faqs:[
  {q:tr("पगार वेळेवर मिळाला नाही तर काय करावे?","वेतन समय पर न मिले तो क्या करें?","What if my salary is not paid on time?"),a:tr("आधी नियोक्त्याला लेखी कळवा. उत्तर न मिळाल्यास कामगार आयुक्त कार्यालयात तक्रार करा; थकीत वेतनासाठी कायदेशीर दावाही करता येतो.","पहले नियोक्ता को लिखित सूचना दें। जवाब न मिलने पर श्रम आयुक्त कार्यालय में शिकायत करें; बकाया वेतन के लिए कानूनी दावा भी किया जा सकता है।","Inform the employer in writing first. If there is no response, complain to the Labour Commissioner's office; a legal claim for unpaid wages can also be made.")},
  {q:tr("PF शिल्लक कशी तपासावी?","PF बैलेंस कैसे जाँचें?","How can I check my PF balance?"),a:tr("EPFO मेंबर पोर्टलवर किंवा UMANG ऍपवर तुमचा UAN वापरून शिल्लक व पासबुक पाहता येते.","EPFO मेंबर पोर्टल या UMANG ऐप पर अपने UAN से बैलेंस व पासबुक देखा जा सकता है।","Use your UAN on the EPFO Member portal or the UMANG app to view your balance and passbook.")}
 ]};

/* --- संविधानाची प्रस्तावना --- */
D.PREAMBLE={
 title:tr("प्रस्तावना","उद्देशिका","Preamble"),
 text:tr("आम्ही, भारताचे लोक, भारताला एक सार्वभौम, समाजवादी, धर्मनिरपेक्ष, लोकशाही गणराज्य म्हणून घडवण्याचा आणि त्याच्या सर्व नागरिकांना — सामाजिक, आर्थिक व राजकीय न्याय; विचार, अभिव्यक्ती, विश्वास, श्रद्धा व उपासना यांचे स्वातंत्र्य; दर्जाची व संधीची समानता — मिळवून देण्याचा, आणि त्या सर्वांमध्ये व्यक्तीची प्रतिष्ठा तसेच राष्ट्राची एकता व एकात्मता सुनिश्चित करणारी बंधुता वाढवण्याचा गंभीर निर्धार करून, आमच्या संविधान सभेत आज २६ नोव्हेंबर १९४९ रोजी हे संविधान स्वीकारत आहोत, अधिनियमित करत आहोत आणि स्वतःप्रत अर्पण करत आहोत.",
   "हम, भारत के लोग, भारत को एक संपूर्ण प्रभुत्व-संपन्न, समाजवादी, पंथनिरपेक्ष, लोकतंत्रात्मक गणराज्य बनाने के लिए, तथा उसके समस्त नागरिकों को: सामाजिक, आर्थिक और राजनैतिक न्याय, विचार, अभिव्यक्ति, विश्वास, धर्म और उपासना की स्वतंत्रता, प्रतिष्ठा और अवसर की समता प्राप्त कराने के लिए, तथा उन सब में व्यक्ति की गरिमा और राष्ट्र की एकता और अखंडता सुनिश्चित करने वाली बंधुता बढ़ाने के लिए दृढ़ संकल्प होकर अपनी इस संविधान सभा में आज तारीख 26 नवंबर, 1949 ई. को एतद्द्वारा इस संविधान को अंगीकृत, अधिनियमित और आत्मार्पित करते हैं।",
   "WE, THE PEOPLE OF INDIA, having solemnly resolved to constitute India into a SOVEREIGN SOCIALIST SECULAR DEMOCRATIC REPUBLIC and to secure to all its citizens: JUSTICE, social, economic and political; LIBERTY of thought, expression, belief, faith and worship; EQUALITY of status and of opportunity; and to promote among them all FRATERNITY assuring the dignity of the individual and the unity and integrity of the Nation; IN OUR CONSTITUENT ASSEMBLY this twenty-sixth day of November, 1949, do HEREBY ADOPT, ENACT AND GIVE TO OURSELVES THIS CONSTITUTION."),
 note:tr("मराठी/हिंदी मजकूर सोप्या वाचनासाठी आहे; अधिकृत मजकुरासाठी भारत सरकारने प्रकाशित केलेले संविधान पहा.","मराठी/हिंदी पाठ सरल पठन हेतु है; आधिकारिक पाठ के लिए भारत सरकार द्वारा प्रकाशित संविधान देखें।","The Marathi/Hindi text is for easy reading; refer to the Constitution published by the Government of India for the official text.")
};
})();
